### ISSUE TITLE
compilation error . bad array type initialization? 

### ISSUE THREAD

**Issue by jbro885** [phunanon/CCircuit#1]
gcc 11.3.0
----------------------------------------------
CCircuit.cpp:159:41: error: array must be initialized with a brace-enclosed initializer   159 |     std::string blob[24] = l_blob[layout];
-----------------------------------------------------------

--------------------------------------------------------------------------------
 const std::string l_blob[2][24] = {
      //Dvorak
        { "[space]", "[enter]", ".oeu", ">OEU", "hH", "A", "L", "f", "F", "CrcR", "gGl_", "tns-", "dDSb", "PpiI", "yYvW", "zZ", "ax", "X", "BkKj", "Mmw" },
      //Qwerty
        { "[space]", "[enter]", "ijkl", "IJKL", "fw", "+", "F", "u", "=", "ghGH", "tTer", "anAE", "dDsb", "Pp-_", "oSOW", "zy", "cv", "Z", "VxXM", "m,<" }
    };
    std::string blob[24] = l_blob[layout];
    uint8_t l = layout;

**Comment by jbro885** [comment]
is there a possible work around?

**Comment by jbro885** [comment]
Never mind. How do you even work this thing?

**Comment by phunanon** [comment]
How do you mean "even work" it? The keybindings are outputted when it loads (I can see from the source).  
It's an old personal project of mine not really built for other people. A user-friendly descendant is [CircuitSim](https://github.com/phunanon/CircuitSim).

**Comment by jbro885** [comment]
how do you "start a design" for example ? 
was able to load "showcase"  (and other designs)
and they all seem to show the same screen. 
I try hitting different keys to get something going only seem to succeed to be able to "type characters on the screen"

I guess my question is how do you load , and initialize a design from the designs folder? (i understand ./CCircuit /design/showcase
(but i dont understand what its supposed to do AFTER that...)
Mind walking us thru an example or something ?
Some GitHub provide more instructions and documentation / examples than others, but it would be cool if you show a quick demo of "how to get started" with one of your designs or a quick transistor or something. thanks

**Comment by jbro885** [comment]
in fact the i dont even know if the designs are loading correctly because every instantiation displays the exact same screen seemingly...

**Comment by jbro885** [comment]
sorry , maybe it would help if i give some context... I'm currently going thru "nand to tetris" and i was hoping to be able to use this to learn how to build ...visualize logic gates... would be cool if i could try to use this as a tool but if you say its only for your use only then i guess i will just move on...

**Comment by jbro885** [comment]
i seem to have gotten my own 'wire" electrified ... cool thanks for this . i will keep at it i suppose. i just wish i knew how to save/ load... i saved my "wire" but it wouldn't load (neither will your designs..." i will keep tinkering with it i suppose. thanks again  🙏🙏
